### ISSUE TITLE
In README.md file, 'fastapi run' command gives error

### ISSUE THREAD

**Issue by lloyddewit** [IDEMSInternational/epicsa-climate-api#2]
@chrismclarke The top-level `README.md` file contains the following Windows installation instructions:
```
    python -m venv .venv
    .\.venv\Scripts\Activate.ps1
    pip install -r requirements.txt
    fastapi run
```
The last line gives me an error. 
Should it be something like `uvicorn app.main:app --reload`?
Or have I missed something?

----

FYI, the error was 'The term 'fastapi' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.'.

I would normally start to investigate the path, but I remembered that for Open CDMS we ran `uvicorn` so I thought I'd check with you first.

**Comment by chrismclarke** [comment]
The cmdlet error usually means windows wasn't able to find the executable from the list of PATH environment variables, so could be an issue with how the virtual environment handles such things, and whether there's any inconsistencies with different versions of windows, python, fastapi etc. 

It still works on my local machine, but I'd say no point deep-diving this one too much. If running the direct `uvicorn` script works for you then I'd say feel free to update the docs accordingly
